### ISSUE TITLE
Make Use of Preset Location

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#1]
Position nodes using the positions found in the pathway descriptions using the "preset" location.

**Comment by sidd-2203** [comment]
I used the preset locations provided in the Pathway Data as shown below and also Provided the screenshot of the code responsible for the initial layout.
![presetLayout1](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/a9a36af9-a9e3-4332-8449-90e24795b274)
![presetLayout2](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/bfdf1c4f-74d8-4ea6-ac52-0ca4faf21b46)
