### ISSUE TITLE
Draw Diagram in PathwayMapper and Use in CellMinerCDB

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#10]
Is it possible to draw a diagram in https://www.pathwaymapper.org/ and then use in CellMinerCDB? I am not sure what export option would make it the easiest to reuse.

**Comment by sidd-2203** [comment]
I added the upload button feature in the Example module which will read the text files generated from the pathway mapper and draw the corresponding network.
![pathwaymapper](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/44d67628-7825-414a-88b6-d267c46af204)
![pathwaymapper2](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/7895c8de-c5f1-4e42-8523-b096acf5466b)
