### ISSUE TITLE
Rename LFC variable in basicStyle.js

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#11]
Rename lfc variable in basicStyle.js to average_value

**Comment by sidd-2203** [comment]
Renamed to avgValues.Find below the code screenshots.
![rename1](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/0217f38f-44e1-48ee-ba61-8fff980c53a2)
![rename2](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/01f67841-2cad-4a9d-903b-85607b454c83)
