### ISSUE TITLE
Calculate the Maximum and Minimum for all Genes in All Pathways to set basicStyle.js

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#12]
Calculate the maximum and minimum for all genes in all pathways to set basicStyle.js

**Comment by sidd-2203** [comment]
Rather than using that can't we just normalize the entire data between -1 to 1 ignore the NA values and then handling new values will also become easy !!

**Comment by sidd-2203** [comment]
Calculated the average and median of all the genes in the pathways whose data is available in the dataset, they are 213 genes, Max Average is  0.02993, and the minimum is -0.03452. I have calculated it to 5 decimal places for better understanding as to 3 decimal places many averages collided to 0.000.
I am attaching the link to the google sheets with averages and medians of these genes.   
Link -> [Gene Data](https://docs.google.com/spreadsheets/d/1AXAx2ZBeYZPtbx9KFeZ1CEz5MsrykEqQ6eMptPmjjZE/edit?usp=sharing)
