### ISSUE TITLE
COADREAD WNT Pathway Complexes (Gene Groups) Error Matching Colors

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#18]
Check if the gene groups are causing issues matching colors from R data to pathway/network for nodes

**Comment by sidd-2203** [comment]
Yes, the gene groups were causing the issue, I fixed it!
PFA the screenshot depicting the same. 
![BugFixed](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/82763685-8968-4670-9604-a32cde6608f1)
