### ISSUE TITLE
Make a Google Slides Presentation for Current Progress

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#19]
* Make a small presentation (5-10 slides)
* Avoid bullet points with more than 7 words 
* Have a title slide 
* Have an intro slide describing project goals 
* Show one screenshot on various slides and highlight parts of the slides to describe the different features on later slide
  * Layout
  * Color of nodes
  * Custom diagrams

**Comment by sidd-2203** [comment]
Slides successfully presented.
[Link to slides](https://docs.google.com/presentation/d/13moRZKvMWy3SpHLIyWioW4LPo9KS_sbxlLdoRAurRNE/edit?usp=sharing)
