### ISSUE TITLE
Color Interactions on Network based on the Type

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#2]
Use the following colors: 

* red: inhibits
* green: activates
* black: binds, 
* green-dashed: induces
* red-dashed: represses 

The dash style will need a custom network style: 

https://js.cytoscape.org/#style/edge-line

See documentation: https://github.com/cytoscape/cyjShiny

**Comment by sidd-2203** [comment]
Colored the edges based on Actions, find below the screenshot depicting the same.
![colored actions](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/c93eccdd-d88c-4afe-b01d-2c3cb64ad53d)
