### ISSUE TITLE
Begin Integrating the Demo Code with the CDB Application as a Module

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#20]
Begin integrating the demo code with the CDB application as a module. This does not need to run on shinyapps.io

**Comment by sidd-2203** [comment]
The Demo Code is completely integrated with the CellMinerCDB application as a module. Please find the source code to it on [this](https://github.com/sidd-2203/cellminercdb/tree/GSoC-Staging) link.
