### ISSUE TITLE
Make option to select by cell line or tissue

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#22]
This has to be done in two menus: 

1.  Options: Cell Line or Tissue
2. Show a conditional menu (https://shiny.posit.co/r/reference/shiny/1.4.0/conditionalpanel)
    1. If Cell Line then it is the sample names
    2. If Tissue then OncoTree values: 

```
lineAnnot <- getSampleData(gdscDataDec15::molData)
lineAnnot$OncoTree1
```

**Comment by sidd-2203** [comment]
@cannin These oncoTree1 values are only labels, How should I use them? Confused a bit.
Screenshot of the oncoTree1 labels -> 
![OncoTree1](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/d7e2d870-6359-4877-a662-597d41d927c3)
Screenshot of the current ConditionalPanel -> 
![ConditionalPanel](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/1213e220-9c4b-4178-8d26-edc0281e85eb)
![ConditionalPanel1](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/5efeb11d-7bd8-4acf-8bfd-253573074e41)

**Comment by cannin** [comment]
@sidd-2203 If you see "Skin" then you would create a data subset with only "Skin" annotated samples and calculate the median/average only with "Skin" samples.

**Comment by sidd-2203** [comment]
Updated UI ->
![Screenshot (22)](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/f7a3f994-9ed5-4b7e-9692-b7075b32ae45)
