### ISSUE TITLE
Simplify Demo for Users by Only Showing the TCGA Pancancer Networks

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#23]
For the CDB group, an initial demo might be easier to showing just the 10 TCGA pancancer networks. Keep any files for the other networks, just do not load them. Please make a comment here if any of the 10 TCGA networks have disconnected nodes like the WNT one.

**Comment by sidd-2203** [comment]
They don't have disconnected nodes but they consist of groups (family in this case),which I'm working on how to depict.

**Comment by sidd-2203** [comment]
Check out the Demo at the [link](https://gsoc-cdb.shinyapps.io/gsoc-cdb/).
