### ISSUE TITLE
Allow the upper and lower thresholds for colors to be set by user

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#24]
Add menus to that allow user to color the max and min values.

**Comment by cannin** [comment]
Use these sliders to set the max and min to control what gets bright blue and red

https://shiny.posit.co/r/articles/build/sliders/

**Comment by cannin** [comment]
Scale values between 0 and 10 before passing to cytoscape.js

**Comment by sidd-2203** [comment]
Upper and lower threshold values can be set on the slider, and colors are set accordingly.
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/098b2d5a-67c5-4a91-b929-d98a732a5bbd)
Code for rescaling of Values before sending to Cytoscape.js
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/f293f090-2d7e-407d-a7a2-c917fff46655)
