### ISSUE TITLE
Change Green Minimum Color to Blue

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#25]
To help users with color vision issues switch the maximum value to red and minimum value to blue

**Comment by sidd-2203** [comment]
Updated the minimum value to blue instead of green.
![GreenToBlue](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/b9752ab9-eb88-4aa0-be6c-dd09e8abde55)
