### ISSUE TITLE
Show a Color Bar

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#26]
You should be able show an image in the sidebar. The code below should give you an idea how to prototype the image that shows a color bar. 

```
# https://stackoverflow.com/questions/48966645/how-can-i-create-a-legend-without-a-plot-in-r
png("del.png")
plot(NULL, xaxt='n', yaxt='n', bty='n', ylab='', xlab='', xlim=0:1, ylim=0:1)
legend("topleft", legend =c('Max Val', 'Min Val', 'Min Val'), pch=15, pt.cex=3, cex=1.5, bty='n',
       col = c('blue', 'white', 'red'), horiz=TRUE)
mtext("Values", at=0.2, cex=2)
dev.off()
```

**Comment by sidd-2203** [comment]
@cannin  Will something like this shown below work?
![colorBar](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/f44202bc-b22d-45a3-90ee-40c1825a04b6)
Or boxed colors,like those shown below will be better?
![colors-edited](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/5392e322-39b3-4748-b259-3b6a0dfcb011)

**Comment by cannin** [comment]
Yes, that look.

- [x] Use values not just placeholder "Max Val" text
- [x] Reduce margin

**Comment by sidd-2203** [comment]
Updated!
![colorBar](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/fc573c51-75d7-4889-b9a6-bac2745b1ae5)
