### ISSUE TITLE
Change Interaction Colors 

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#27]
Reverse the colors of INDUCES and REPRESSES

**Comment by sidd-2203** [comment]
Updated!
Previously advised color -> 
![originalColor](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/3c02f968-8742-4801-8ad7-6001e2abe681)
New color -> 
![ReversedColor](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/69e7a33a-b8b3-4cae-8a85-71a99e7ac50b)

**Comment by cannin** [comment]
@sidd-2203 My old description of the colors seems right. Repress -> Red. Maybe only the slide was wrong?

**Comment by sidd-2203** [comment]
Yeah, sorry the slide was wrong, your description was correct. Screenshot of the slide ->
![slide](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/f0517092-eb06-452f-a93b-0e274896eedd)

Corrected Code -> 
![correctCode](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/5d229cba-093a-4e62-8dbc-45e4b96fada1)
