### ISSUE TITLE
Make the "Complex" Shape

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#29]
Make it possible to have the complex shape

**Comment by sidd-2203** [comment]
In an attempt to set a cut-rectangle shape to the node, I ended up making all the nodes similar to Pathway Mapper, i.e. All non-parent nodes are also set to shapes as in Pathway Mapper, find below the screenshot depicting the same, Please suggest your views on it.
 
![Genes-Complex](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/2dc1a533-a100-49ac-b022-e932a1e548fe)
Find below the pathway Mapper diagram of the same pathway.
![Genes-Complex-PathwayMapper](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/3549a312-dab0-475f-930e-22102b9a62fc)
