### ISSUE TITLE
Color Nodes with Average across all Samples

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#3]
Color the nodes with the average samples (columns)

**Comment by sidd-2203** [comment]
I have added the average values as a lfc parameter to the node and used it was coloring the nodes in the graph but it shows no response,(edge-color and type based on actions are mentioned in the same file and it is working). Attaching the code below and a response, please suggest the correction. 
Styling code -> 
![styling_code](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/6d0bab33-7f4c-4005-995b-7b95e28b1678)
Output ->
![colored actions](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/3ef692e6-75a3-4133-81dc-72afda8a65c7)

**Comment by cannin** [comment]
@sidd-2203 where is the code? Any success with the shinyapps.io demo?

**Comment by cannin** [comment]
@sidd-2203 "lfc" is a variable name. Is "lfc" entry in the JSON data you visualizing?

**Comment by sidd-2203** [comment]
> @sidd-2203 "lfc" is a variable name. Is "lfc" entry in the JSON data you visualizing?

No it is not in the json file,it is from the average genetic value on the 
![code_lfc](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/84a95428-129e-4579-9b8e-3f058eb9a29d)
basis of which I have to color the node,The code snippet is attached below

**Comment by sidd-2203** [comment]
> @sidd-2203 where is the code? Any success with the shinyapps.io demo?

I tried it but found some error with a dependency, I have mentioned it in [that](https://github.com/cannin/gsoc_2023_cellminercdb_networks/issues/9#issuecomment-1568424030) issue, and I'm also trying to solve the @issue.

**Comment by sidd-2203** [comment]
Nodes are colored as shown in the previous meeting. Also, find the final screenshot below. 
![finalSS](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/55ca4f95-40f6-4cea-a049-b3f20ed6cacf)

**Comment by cannin** [comment]
@sidd-2203 is the "proliferation ..." circle red in the last screenshot? If so, how if it has no value?

**Comment by sidd-2203** [comment]
Coloring of nodes is done for all the pathways only a particular pathway with compound modules is producing a bug which is to be solved under [this ](https://github.com/cannin/gsoc_2023_cellminercdb_networks/issues/18)issue.
