### ISSUE TITLE
Change Table Output to Reflect 1 Cell Line or Many Samples (by Tissue)

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#31]
Change the data.frame that gets generated dependent on number of samples

- [x] Columns for 1 sample: "Value"
- [x] Columns for many samples: Also, just put "Median" and "Average"

**Comment by sidd-2203** [comment]
Updated!
![CellLine-Value](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/0bc9af8c-61f1-49b5-8699-e92dde32a215)
![CellLine-Tissue](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/208ba88b-eb8c-47e3-9291-a94d09d311a5)
