### ISSUE TITLE
Make a Demo Pathway with All PathwayMapper Symbols

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#32]
Use [pathwaymapper.](http://pathwaymapper.org/) that includes all the symbols

**Comment by sidd-2203** [comment]
I've included below the screenshot of a Demo Pathway, Consisting of all the components of the pathway mapper.
![PathwayWithAllComponents](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/0ca6d6d4-793b-4570-a333-89b69c13dc22)

**Comment by cannin** [comment]
Generally good, just make the lines all go 90 or 180 degrees

**Comment by sidd-2203** [comment]
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/9ed3cc2b-0aae-4d38-8125-52578063df1f)

**Comment by sidd-2203** [comment]
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/fade766a-d0be-4589-914f-98ae25abdc94)
