### ISSUE TITLE
Move Upload Pathway to a Conditional Menu

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#33]
Make the workflow such that a user either selects 1 of the 10 main pathways or uploads a pathway from PathwayMapper

**Comment by sidd-2203** [comment]
Upload pathway moved above to the conditional menu
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/cf8e0054-bd45-4748-b2be-13c94c0fdf18)
