### ISSUE TITLE
Add the CCLE Dataset to the Project 

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#34]
Add the CCLE dataset in the selection of data

**Comment by cannin** [comment]
Do not make a tissue to sample mapping; use the existing data from ccleData. Also, make a srcContent that includes the CCLE dataset.

**Comment by sidd-2203** [comment]
Loaded srcContent with CCLE dataset.

![ccleDataset](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/43577b16-26ca-49e7-b6f9-88fdc9228136)
