### ISSUE TITLE
Commit Existing Shiny App Demo Code to CellMinerCDB Fork

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#35]
Commit existing Shiny App Demo code to CellMinerCDB fork

**Comment by cannin** [comment]
Remove files:

- [x] R shiny learning from fork
- [x] data.csv
- [x] testing.R (???)
- [ ] oncotree1_colors.txt

**Comment by sidd-2203** [comment]
oncotree1_colors.txt is needed in the code.

**Comment by sidd-2203** [comment]
Updated on the branch [GSOC-Staging](https://github.com/sidd-2203/cellminercdb).
