### ISSUE TITLE
Change Menu Labels

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#49]
* Use radio buttons rather than dropdown menu with "Use Built-in Pathway List" or "Upload Pathway"
* "Select Pathway" -> "Select Pathway Source"
* "Choose a file" -> "Upload PathwayMapper.com File"

**Comment by sidd-2203** [comment]
Changed Menu Labels as instructed above.
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/b5fcd22d-6f51-4f07-843b-e532cfc9af0b)
