### ISSUE TITLE
Remove Select First Neighbor

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#5]
Remove Select First Neighbor

**Comment by sidd-2203** [comment]
Removed Select first neighbor, find below the before and after screenshots of the same 
Before Removing 
![sfn_before](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/f27e38d9-251f-4055-89c9-cb5c68ee38ca)
After Removing
![sfn_after](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/0a3369b4-cb5e-4a0b-b34b-ef6c060a1953)
