### ISSUE TITLE
Add Documentation for Adding Pathways from Pathway Mapper to the Builtin Pathway List

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#50]

**Comment by sidd-2203** [comment]
Should I add it to the project guide? because I don't think this information is needed by everyone who visits CellMinerCDB.
Also where to write about how to create a pathway using pathwaymapper.org?

**Comment by sidd-2203** [comment]
Discussed and shown to you and Fathi, where more should I add the documentation for this purpose?

**Comment by cannin** [comment]
@sidd-2203 for now you could just put it in the README to this repo

**Comment by sidd-2203** [comment]
Updated the README of this repo with the steps.
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/3b8c956e-28b2-462d-ae3a-310d13df4312)
