### ISSUE TITLE
Add Code to Convert Single Pathway to Correct Format

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#52]
@sidd-2203 Does this code convert a pathway file to the correct format? A "for" loop would be necessary for many files.

```
library(jsonlite)

input_file <- "pathway.txt"
output_file <- "pathway_as_json.json"
  
t1 <- readLines(input_file)
t2 <- list(t1)
names(t2) <- t1[1]

t3 <- toJSON(t2)

writeLines(t3, output_file)
```

**Comment by sidd-2203** [comment]
No, It doesn't as the text file generated by Pathway mapper has more columns than those present in the pathways.json file, so will need to prune them. Attached is the screenshot of the file exported from the pathway mapper and also of that of pathway.json
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/11d88436-4739-4658-8247-1810fd6d4db6)
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/b14be96d-17f8-45b1-a2ef-824b8b4625fd)

**Comment by sidd-2203** [comment]
I have written the code to create a JSON file of a similar type so that any pathway created can be included in the original file, but the problem to discuss is where should the output be saved, and on what condition to execute this piece of code.
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/e3f9f4fc-8ddc-4446-9d9c-2698fa003646)
Output file of the Example pathway-> 
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/c453618a-e5ed-4525-84f5-4bc8ff3b6a79)

**Comment by cannin** [comment]
If the pathway properties (left hand sidebar) are changed by the user, then can the name of the pathway be extracted? Rather than use the filename. 

<img width="1464" alt="Screenshot 2023-08-25 at 4 32 36 PM" src="https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/790284/2b16d67b-969f-4387-a63b-979e66bec51b">

**Comment by sidd-2203** [comment]
When we change the Pathway Title from the sidebar properties the name of the saved file will be the title, so extracting it from the file name or the Title remains the same until and unless someone purposely changes the name of the file afterward. 
PS: Even if you don't want to take the name of the file, the pathway name is the first line of the file, I can surely extract the name from it. Recommend to me which to use.

**Comment by cannin** [comment]
Take the name from the first line; I think it is safer.

**Comment by sidd-2203** [comment]
Updated the code to create a JSON file of the same type as pathways.json from a file of pathway mapper, people using it just need to execute the code paste this file (pathwayData.json)  data to pathways.json and add a comma accordingly, and execute readingPathway.R, the pathway will be added.
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/af93a52b-fca6-48c7-8a59-0847aba5733d)
