### ISSUE TITLE
Make new pathways.json

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#53]
Make a new pathways.json with only the 10 TCGA pancancer pathways.

**Comment by sidd-2203** [comment]
Later in the meeting, we had a discussion that we should keep all the pathways even if we have to add the name of the pathway in addition, Do we still need a new file?

**Comment by cannin** [comment]
@sidd-2203 yes make a new files with just the 10 pathways

**Comment by sidd-2203** [comment]
Updated the pathways.json file to include only those 10 pathways.
Changes can be found in the [this](https://github.com/CBIIT/cellminercdb/commit/5a1537e86fba467c970c43e0fa50f2a8ff32edac#diff-83bbfa01990ddbbc2e2a20a8220afe786f9c3c1de74db6f09ecd69d6eba66c4b) commit
