### ISSUE TITLE
Save the network with grey nodes to a JSON file

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#54]
The JSON file will help debugging the stylesheet colors

**Comment by sidd-2203** [comment]
The JSON file is completely unstructured as shown below and won't help, I think someone can just suggest how to use the selector on compound nodes only by seeing the style file of our code and the respective pathway.
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/4627f2d2-3452-4f0c-a171-59de20796733)

[style.txt](https://github.com/cannin/gsoc_2023_cellminercdb_networks/files/12441995/style.txt)
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/714a6726-f805-461a-bc17-22af15ca4fe0)

PS: Github doesn't support Js file, so adding the style in a text file.

**Comment by cannin** [comment]
Let's solve #55 first

**Comment by sidd-2203** [comment]
Since #55 is solved thus closing this issue.
