### ISSUE TITLE
Use "Tee" Interaction for Red Inhibitory Interactions

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#56]
For inhibits and represses: 

https://js.cytoscape.org/demos/edge-arrows/

**Comment by sidd-2203** [comment]
Updated the code for represses and Inhibits interaction both colors are red one dashed and one not, and changed the arrow shape to Tee from triangle. 
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/d2d4520a-235b-4c42-a11f-9673f4859c9b)
