### ISSUE TITLE
Black Arrow Bug

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#57]
Why is the bottom arrow black? If it is "binds" then it should not have an arrowhead. If it has an arrowhead, it should either be red or green.

![black_arrow_cdb](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/790284/08bae352-9ea2-42cf-8774-83d6b9c542cd)

**Comment by sidd-2203** [comment]
All the interactions had an arrowhead initially. Updated the code to remove the arrowhead in BINDS and ACTIVATES and REPRESSES has Tee head as shown below.
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/b9ecd857-23c4-4af5-8977-92eb55103523)
