### ISSUE TITLE
Add Symbol Legend to Documentation

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#58]
Add this legend to the tool and/or documentation if you do not have one already. 

![pathway_mapper_legend](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/790284/89133f0a-bb3f-4028-9a41-2959b3bfbc95)

**Comment by sidd-2203** [comment]
Updated the documentation and tool with Legend.
Tool :
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/5a56f78f-d522-4e77-81a9-c4af8fd58e7c)
 
Documentation : 
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/86f5ff92-4646-4e12-9403-11117c2209c9)
