### ISSUE TITLE
Round Table to Values 3 Decimal Places

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#6]
Round table to values 3 decimal places

**Comment by sidd-2203** [comment]
Rounded the Table values upto 3 decimal places , Screenshot of the resulting table is shown below
![Updated Table ](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/d31a556c-024c-47ca-85f6-2a471f6d7e1e)
