### ISSUE TITLE
Change Values Shown Above Figure

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#62]
Show the "pval" and "NES" values and the pathway title 

Expected text with 3 decimal digits: 

```
PATHWAY_TITLE 
p-Value: NUMBER
Normalize Enrichment Score: NUMBER
```

use h1(PATHWAY_TITLE)

**Comment by sidd-2203** [comment]
The view is as shown below 
![image](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/01aee335-4fe1-4d0b-be19-c0e0e0037e59)
