### ISSUE TITLE
Describe Exacting Matching of Identifiers in Documentation

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_cellminercdb_networks#64]
State

```
For custom pathways you upload, make sure pathway members use official gene symbols; these are typically uppercase (e.g., TP53 and not tp53). 
```

**Comment by sidd-2203** [comment]
Updated the guide. This can be seen in [this ](https://github.com/CBIIT/cellminercdb/commit/8165ab93d749b6174625190e298ab5b0e91365a1#diff-8f8a6e20aaba41c5902bdb74b2031c9b5c9562284478a20cbdb1dd92445fafda)commit.
