### ISSUE TITLE
Make a demo on shinyappio

### ISSUE THREAD

**Issue by sidd-2203** [cannin/gsoc_2023_cellminercdb_networks#9]

**Comment by sidd-2203** [comment]
@cannin While uploading an example project on shinyapps.io I get the following error
![Error in deploying on shinyappio](https://github.com/cannin/gsoc_2023_cellminercdb_networks/assets/75191039/2c47f31b-d5ac-443b-b15f-81c20dd61501)
Please can you suggest a way to solve it?

**Comment by sidd-2203** [comment]
A demo application is hosted on Shinyapp.io and can be accessed using [this](http://gsoc-cdb.shinyapps.io/gsoc-cdb) link.

**Comment by cannin** [comment]
I see the demo, but no values on the nodes
